//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\ATMOS\\ATMOS_ES.ec3")]
        public string AtmosES {
            get {
                return ((string)(this["AtmosES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\ATMOS\\WithTimeCode.ec3")]
        public string AtmosESTC {
            get {
                return ((string)(this["AtmosESTC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\MOV\\Big Buck Bunny\\bbb_6Ch" +
            ".mov\"")]
        public string Mov6Ch {
            get {
                return ((string)(this["Mov6Ch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\HDRMP4\\FULLSMPTECOLORDATA.m" +
            "p4")]
        public string HDRMP4 {
            get {
                return ((string)(this["HDRMP4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\Artifacts\\clean_telecine.av" +
            "i")]
        public string Artifacts_CleanTelecine {
            get {
                return ((string)(this["Artifacts_CleanTelecine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\Artifacts\\Anamorphic_Letter" +
            "boxed.mpg")]
        public string Artifacts_Anamorphic_Letterbox {
            get {
                return ((string)(this["Artifacts_Anamorphic_Letterbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\azvmfile\\Engineer\\TestSamples\\LibMediaProcessorTest\\Artifacts\\Letterbox_Noise.m" +
            "pg")]
        public string Artifacts_Letterbox_Noise {
            get {
                return ((string)(this["Artifacts_Letterbox_Noise"]));
            }
        }
    }
}
