//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Mediainfo {
    
    private MediainfoFileTrack[] fileField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("track", typeof(MediainfoFileTrack), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public MediainfoFileTrack[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MediainfoFileTrack {
    
    private string countField;
    
    private string streamCountField;
    
    private string streamKindField;
    
    private string streamKind_StringField;
    
    private string streamKindIDField;
    
    private string streamOrderField;
    
    private string idField;
    
    private string iD_StringField;
    
    private string videoCountField;
    
    private string audioCountField;
    
    private string video_Format_ListField;
    
    private string video_Format_WithHint_ListField;
    
    private string video_Codec_ListField;
    
    private string audio_Format_ListField;
    
    private string audio_Format_WithHint_ListField;
    
    private string audio_Codec_ListField;
    
    private string completeNameField;
    
    private string folderNameField;
    
    private string fileNameField;
    
    private string fileExtensionField;
    
    private string formatField;
    
    private string format_InfoField;
    
    private string format_UrlField;
    
    private string format_StringField;
    
    private string format_ExtensionsField;
    
    private string format_CommercialField;
    
    private string format_ProfileField;
    
    private string internetMediaTypeField;
    
    private string codecIDField;
    
    private string codecID_InfoField;
    
    private string codecID_StringField;
    
    private string codecID_UrlField;
    
    private string codecID_CompatibleField;
    
    private string codecField;
    
    private string codec_StringField;
    
    private string codec_FamilyField;
    
    private string codec_CCField;
    
    private string codec_ProfileField;
    
    private string codec_ExtensionsField;
    
    private string fileSizeField;
    
    private string fileSize_StringField;
    
    private string fileSize_String1Field;
    
    private string fileSize_String2Field;
    
    private string fileSize_String3Field;
    
    private string fileSize_String4Field;
    
    private string durationField;
    
    private string duration_StringField;
    
    private string duration_String1Field;
    
    private string duration_String2Field;
    
    private string duration_String3Field;
    
    private string duration_String4Field;
    
    private string duration_String5Field;
    
    private string bitRate_ModeField;
    
    private string bitRate_Mode_StringField;
    
    private string bitRateField;
    
    private string bitRate_StringField;
    
    private string channel_s_Field;
    
    private string channel_s__StringField;
    
    private string channel_s__OriginalField;
    
    private string channel_s__Original_StringField;
    
    private string channelPositionsField;
    
    private string channelPositions_String2Field;
    
    private string channelLayoutField;
    
    private string samplesPerFrameField;
    
    private string samplingRateField;
    
    private string samplingRate_StringField;
    
    private string samplingCountField;
    
    private string widthField;
    
    private string width_StringField;
    
    private string heightField;
    
    private string height_StringField;
    
    private string sampled_WidthField;
    
    private string sampled_HeightField;
    
    private string pixelAspectRatioField;
    
    private string displayAspectRatioField;
    
    private string displayAspectRatio_StringField;
    
    private string rotationField;
    
    private string frameRate_ModeField;
    
    private string frameRate_Mode_StringField;
    
    private string overallBitRate_ModeField;
    
    private string overallBitRate_Mode_StringField;
    
    private string overallBitRateField;
    
    private string overallBitRate_StringField;
    
    private string frameRateField;
    
    private string frameRate_StringField;
    
    private string frameRate_OriginalField;
    
    private string frameRate_Original_StringField;
    
    private string frameRate_Original_NumField;
    
    private string frameRate_Original_DenField;
    
    private string frameCountField;
    
    private string compression_ModeField;
    
    private string compression_Mode_StringField;
    
    private string resolutionField;
    
    private string resolution_StringField;
    
    private string colorimetryField;
    
    private string colorSpaceField;
    
    private string chromaSubsamplingField;
    
    private string chromaSubsampling_StringField;
    
    private string chromaSubsampling_PositionField;
    
    private string bitDepthField;
    
    private string bitDepth_StringField;
    
    private string bits_Pixel_Frame_Field;
    
    private string streamSizeField;
    
    private string streamSize_StringField;
    
    private string streamSize_String1Field;
    
    private string streamSize_String2Field;
    
    private string streamSize_String3Field;
    
    private string streamSize_String4Field;
    
    private string streamSize_String5Field;
    
    private string streamSize_ProportionField;
    
    private string defaultField;
    
    private string default_StringField;
    
    private string alternateGroupField;
    
    private string alternateGroup_StringField;
    
    private string encoded_LibraryField;
    
    private string encoded_Library_StringField;
    
    private string encoded_Library_NameField;
    
    private string encoded_Library_VersionField;
    
    private string colour_rangeField;
    
    private string colour_description_presentField;
    
    private string colour_primariesField;
    
    private string transfer_characteristicsField;
    
    private string matrix_coefficientsField;
    
    private string masteringDisplay_ColorPrimariesField;
    
    private string masteringDisplay_LuminanceField;

    private string MaxCLLField;

    private string MaxFALLField;

    private string headerSizeField;
    
    private string dataSizeField;
    
    private string footerSizeField;
    
    private string isStreamableField;
    
    private string file_Created_DateField;
    
    private string file_Created_Date_LocalField;
    
    private string file_Modified_DateField;
    
    private string file_Modified_Date_LocalField;
    
    private string encoded_ApplicationField;
    
    private string encoded_Application_StringField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamCount {
        get {
            return this.streamCountField;
        }
        set {
            this.streamCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamKind {
        get {
            return this.streamKindField;
        }
        set {
            this.streamKindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamKind_String {
        get {
            return this.streamKind_StringField;
        }
        set {
            this.streamKind_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamKindID {
        get {
            return this.streamKindIDField;
        }
        set {
            this.streamKindIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamOrder {
        get {
            return this.streamOrderField;
        }
        set {
            this.streamOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID_String {
        get {
            return this.iD_StringField;
        }
        set {
            this.iD_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VideoCount {
        get {
            return this.videoCountField;
        }
        set {
            this.videoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AudioCount {
        get {
            return this.audioCountField;
        }
        set {
            this.audioCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Video_Format_List {
        get {
            return this.video_Format_ListField;
        }
        set {
            this.video_Format_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Video_Format_WithHint_List {
        get {
            return this.video_Format_WithHint_ListField;
        }
        set {
            this.video_Format_WithHint_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Video_Codec_List {
        get {
            return this.video_Codec_ListField;
        }
        set {
            this.video_Codec_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Audio_Format_List {
        get {
            return this.audio_Format_ListField;
        }
        set {
            this.audio_Format_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Audio_Format_WithHint_List {
        get {
            return this.audio_Format_WithHint_ListField;
        }
        set {
            this.audio_Format_WithHint_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Audio_Codec_List {
        get {
            return this.audio_Codec_ListField;
        }
        set {
            this.audio_Codec_ListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompleteName {
        get {
            return this.completeNameField;
        }
        set {
            this.completeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FolderName {
        get {
            return this.folderNameField;
        }
        set {
            this.folderNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileExtension {
        get {
            return this.fileExtensionField;
        }
        set {
            this.fileExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_Info {
        get {
            return this.format_InfoField;
        }
        set {
            this.format_InfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_Url {
        get {
            return this.format_UrlField;
        }
        set {
            this.format_UrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_String {
        get {
            return this.format_StringField;
        }
        set {
            this.format_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_Extensions {
        get {
            return this.format_ExtensionsField;
        }
        set {
            this.format_ExtensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_Commercial {
        get {
            return this.format_CommercialField;
        }
        set {
            this.format_CommercialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Format_Profile {
        get {
            return this.format_ProfileField;
        }
        set {
            this.format_ProfileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternetMediaType {
        get {
            return this.internetMediaTypeField;
        }
        set {
            this.internetMediaTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodecID {
        get {
            return this.codecIDField;
        }
        set {
            this.codecIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodecID_Info {
        get {
            return this.codecID_InfoField;
        }
        set {
            this.codecID_InfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodecID_String {
        get {
            return this.codecID_StringField;
        }
        set {
            this.codecID_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodecID_Url {
        get {
            return this.codecID_UrlField;
        }
        set {
            this.codecID_UrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodecID_Compatible {
        get {
            return this.codecID_CompatibleField;
        }
        set {
            this.codecID_CompatibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec {
        get {
            return this.codecField;
        }
        set {
            this.codecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec_String {
        get {
            return this.codec_StringField;
        }
        set {
            this.codec_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec_Family {
        get {
            return this.codec_FamilyField;
        }
        set {
            this.codec_FamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec_CC {
        get {
            return this.codec_CCField;
        }
        set {
            this.codec_CCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec_Profile {
        get {
            return this.codec_ProfileField;
        }
        set {
            this.codec_ProfileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Codec_Extensions {
        get {
            return this.codec_ExtensionsField;
        }
        set {
            this.codec_ExtensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize {
        get {
            return this.fileSizeField;
        }
        set {
            this.fileSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize_String {
        get {
            return this.fileSize_StringField;
        }
        set {
            this.fileSize_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize_String1 {
        get {
            return this.fileSize_String1Field;
        }
        set {
            this.fileSize_String1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize_String2 {
        get {
            return this.fileSize_String2Field;
        }
        set {
            this.fileSize_String2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize_String3 {
        get {
            return this.fileSize_String3Field;
        }
        set {
            this.fileSize_String3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileSize_String4 {
        get {
            return this.fileSize_String4Field;
        }
        set {
            this.fileSize_String4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String {
        get {
            return this.duration_StringField;
        }
        set {
            this.duration_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String1 {
        get {
            return this.duration_String1Field;
        }
        set {
            this.duration_String1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String2 {
        get {
            return this.duration_String2Field;
        }
        set {
            this.duration_String2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String3 {
        get {
            return this.duration_String3Field;
        }
        set {
            this.duration_String3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String4 {
        get {
            return this.duration_String4Field;
        }
        set {
            this.duration_String4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration_String5 {
        get {
            return this.duration_String5Field;
        }
        set {
            this.duration_String5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitRate_Mode {
        get {
            return this.bitRate_ModeField;
        }
        set {
            this.bitRate_ModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitRate_Mode_String {
        get {
            return this.bitRate_Mode_StringField;
        }
        set {
            this.bitRate_Mode_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitRate {
        get {
            return this.bitRateField;
        }
        set {
            this.bitRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitRate_String {
        get {
            return this.bitRate_StringField;
        }
        set {
            this.bitRate_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Channel_s_ {
        get {
            return this.channel_s_Field;
        }
        set {
            this.channel_s_Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Channel_s__String {
        get {
            return this.channel_s__StringField;
        }
        set {
            this.channel_s__StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Channel_s__Original {
        get {
            return this.channel_s__OriginalField;
        }
        set {
            this.channel_s__OriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Channel_s__Original_String {
        get {
            return this.channel_s__Original_StringField;
        }
        set {
            this.channel_s__Original_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelPositions {
        get {
            return this.channelPositionsField;
        }
        set {
            this.channelPositionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelPositions_String2 {
        get {
            return this.channelPositions_String2Field;
        }
        set {
            this.channelPositions_String2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelLayout {
        get {
            return this.channelLayoutField;
        }
        set {
            this.channelLayoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SamplesPerFrame {
        get {
            return this.samplesPerFrameField;
        }
        set {
            this.samplesPerFrameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SamplingRate {
        get {
            return this.samplingRateField;
        }
        set {
            this.samplingRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SamplingRate_String {
        get {
            return this.samplingRate_StringField;
        }
        set {
            this.samplingRate_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SamplingCount {
        get {
            return this.samplingCountField;
        }
        set {
            this.samplingCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width_String {
        get {
            return this.width_StringField;
        }
        set {
            this.width_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Height_String {
        get {
            return this.height_StringField;
        }
        set {
            this.height_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sampled_Width {
        get {
            return this.sampled_WidthField;
        }
        set {
            this.sampled_WidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sampled_Height {
        get {
            return this.sampled_HeightField;
        }
        set {
            this.sampled_HeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PixelAspectRatio {
        get {
            return this.pixelAspectRatioField;
        }
        set {
            this.pixelAspectRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayAspectRatio {
        get {
            return this.displayAspectRatioField;
        }
        set {
            this.displayAspectRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayAspectRatio_String {
        get {
            return this.displayAspectRatio_StringField;
        }
        set {
            this.displayAspectRatio_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Mode {
        get {
            return this.frameRate_ModeField;
        }
        set {
            this.frameRate_ModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Mode_String {
        get {
            return this.frameRate_Mode_StringField;
        }
        set {
            this.frameRate_Mode_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OverallBitRate_Mode {
        get {
            return this.overallBitRate_ModeField;
        }
        set {
            this.overallBitRate_ModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OverallBitRate_Mode_String {
        get {
            return this.overallBitRate_Mode_StringField;
        }
        set {
            this.overallBitRate_Mode_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OverallBitRate {
        get {
            return this.overallBitRateField;
        }
        set {
            this.overallBitRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OverallBitRate_String {
        get {
            return this.overallBitRate_StringField;
        }
        set {
            this.overallBitRate_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate {
        get {
            return this.frameRateField;
        }
        set {
            this.frameRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_String {
        get {
            return this.frameRate_StringField;
        }
        set {
            this.frameRate_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Original {
        get {
            return this.frameRate_OriginalField;
        }
        set {
            this.frameRate_OriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Original_String {
        get {
            return this.frameRate_Original_StringField;
        }
        set {
            this.frameRate_Original_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Original_Num {
        get {
            return this.frameRate_Original_NumField;
        }
        set {
            this.frameRate_Original_NumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameRate_Original_Den {
        get {
            return this.frameRate_Original_DenField;
        }
        set {
            this.frameRate_Original_DenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FrameCount {
        get {
            return this.frameCountField;
        }
        set {
            this.frameCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Compression_Mode {
        get {
            return this.compression_ModeField;
        }
        set {
            this.compression_ModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Compression_Mode_String {
        get {
            return this.compression_Mode_StringField;
        }
        set {
            this.compression_Mode_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Resolution_String {
        get {
            return this.resolution_StringField;
        }
        set {
            this.resolution_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Colorimetry {
        get {
            return this.colorimetryField;
        }
        set {
            this.colorimetryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ColorSpace {
        get {
            return this.colorSpaceField;
        }
        set {
            this.colorSpaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChromaSubsampling {
        get {
            return this.chromaSubsamplingField;
        }
        set {
            this.chromaSubsamplingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChromaSubsampling_String {
        get {
            return this.chromaSubsampling_StringField;
        }
        set {
            this.chromaSubsampling_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChromaSubsampling_Position {
        get {
            return this.chromaSubsampling_PositionField;
        }
        set {
            this.chromaSubsampling_PositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitDepth {
        get {
            return this.bitDepthField;
        }
        set {
            this.bitDepthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BitDepth_String {
        get {
            return this.bitDepth_StringField;
        }
        set {
            this.bitDepth_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bits_Pixel_Frame_ {
        get {
            return this.bits_Pixel_Frame_Field;
        }
        set {
            this.bits_Pixel_Frame_Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize {
        get {
            return this.streamSizeField;
        }
        set {
            this.streamSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String {
        get {
            return this.streamSize_StringField;
        }
        set {
            this.streamSize_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String1 {
        get {
            return this.streamSize_String1Field;
        }
        set {
            this.streamSize_String1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String2 {
        get {
            return this.streamSize_String2Field;
        }
        set {
            this.streamSize_String2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String3 {
        get {
            return this.streamSize_String3Field;
        }
        set {
            this.streamSize_String3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String4 {
        get {
            return this.streamSize_String4Field;
        }
        set {
            this.streamSize_String4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_String5 {
        get {
            return this.streamSize_String5Field;
        }
        set {
            this.streamSize_String5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StreamSize_Proportion {
        get {
            return this.streamSize_ProportionField;
        }
        set {
            this.streamSize_ProportionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Default_String {
        get {
            return this.default_StringField;
        }
        set {
            this.default_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AlternateGroup {
        get {
            return this.alternateGroupField;
        }
        set {
            this.alternateGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AlternateGroup_String {
        get {
            return this.alternateGroup_StringField;
        }
        set {
            this.alternateGroup_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Library {
        get {
            return this.encoded_LibraryField;
        }
        set {
            this.encoded_LibraryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Library_String {
        get {
            return this.encoded_Library_StringField;
        }
        set {
            this.encoded_Library_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Library_Name {
        get {
            return this.encoded_Library_NameField;
        }
        set {
            this.encoded_Library_NameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Library_Version {
        get {
            return this.encoded_Library_VersionField;
        }
        set {
            this.encoded_Library_VersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string colour_range {
        get {
            return this.colour_rangeField;
        }
        set {
            this.colour_rangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string colour_description_present {
        get {
            return this.colour_description_presentField;
        }
        set {
            this.colour_description_presentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string colour_primaries {
        get {
            return this.colour_primariesField;
        }
        set {
            this.colour_primariesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string transfer_characteristics {
        get {
            return this.transfer_characteristicsField;
        }
        set {
            this.transfer_characteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string matrix_coefficients {
        get {
            return this.matrix_coefficientsField;
        }
        set {
            this.matrix_coefficientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MasteringDisplay_ColorPrimaries {
        get {
            return this.masteringDisplay_ColorPrimariesField;
        }
        set {
            this.masteringDisplay_ColorPrimariesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MasteringDisplay_Luminance {
        get {
            return this.masteringDisplay_LuminanceField;
        }
        set {
            this.masteringDisplay_LuminanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaxCLL
    {
        get
        {
            return this.MaxCLLField;
        }
        set
        {
            this.MaxCLLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaxFALL
    {
        get
        {
            return this.MaxFALLField;
        }
        set
        {
            this.MaxFALLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeaderSize {
        get {
            return this.headerSizeField;
        }
        set {
            this.headerSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataSize {
        get {
            return this.dataSizeField;
        }
        set {
            this.dataSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FooterSize {
        get {
            return this.footerSizeField;
        }
        set {
            this.footerSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsStreamable {
        get {
            return this.isStreamableField;
        }
        set {
            this.isStreamableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string File_Created_Date {
        get {
            return this.file_Created_DateField;
        }
        set {
            this.file_Created_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string File_Created_Date_Local {
        get {
            return this.file_Created_Date_LocalField;
        }
        set {
            this.file_Created_Date_LocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string File_Modified_Date {
        get {
            return this.file_Modified_DateField;
        }
        set {
            this.file_Modified_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string File_Modified_Date_Local {
        get {
            return this.file_Modified_Date_LocalField;
        }
        set {
            this.file_Modified_Date_LocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Application {
        get {
            return this.encoded_ApplicationField;
        }
        set {
            this.encoded_ApplicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Encoded_Application_String {
        get {
            return this.encoded_Application_StringField;
        }
        set {
            this.encoded_Application_StringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private Mediainfo[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mediainfo")]
    public Mediainfo[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
